name: test-app
services:
  web:
    image: nginx:latest
    container_name: test-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  redis:
    image: redis:alpine
    container_name: test-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
